sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '12'
  - '14'
script:
  - npm test
branches:
  only:
    - master
    - /^greenkeeper/.*$/
